added Ruby and Perl in safe mode

diff --git a/encrypt_script b/encrypt_script
--- a/encrypt_script
+++ b/encrypt_script
@@ -184,6 +184,14 @@ if (substr($msg, 0, 2) eq '#!') {
   $lang = 'sh';
 }
 
+# Add a leading newline as a separator. This screws up line numbering, but
+# we can't add `;' because it's not possible to have a compound statement in
+# the same line. Usually we won't prepend anything, because there is a shebang
+# or a following \n.
+substr($msg, 0, 0) = "\n" if $lang eq 'python' and
+    $msg =~ m/\A(?:\@|(?:from|while|import|with|if|try|class|def|for)\b)/;
+    # $msg !~ m@\A[ \t]*(?:#.*)$@m;
+
 if ($mode eq 'safe') {
   my $gp;
   my($r,$w);
@@ -215,11 +223,12 @@ test $? = 0||exit 255;eval "unset P;$P";exit
 END
     print $gpg_sh_code, $e;
   } elsif ($lang eq 'python') {
+    # TODO(pts): Change argv[0] for all 3 languages.
     my $gpg_python_code = <<'END';
-#! /bin/sh
+#!/bin/sh --
 """"exec python -- "$0" "$@";exit "1"""
 import sys,os;f=open(__file__);r,w=os.pipe();q=os.fork()
-if q:os.close(w);os.dup2(r,0);\
+if q:os.close(w);os.dup2(r,0);r==0 or os.close(r);\
 os.execlp('python','python','-',str(q),*sys.argv[1:])
 os.write(w,'exec"import os,sys;a=sys.argv;p=int(a.pop(1))\\n\
 if(p,0)!=os.waitpid(p,0):sys.exit(255)"in{};\n')
@@ -229,6 +238,42 @@ if w!=1:os.dup2(w,1);os.close(w)
 os.execlp('gpg','gpg','--armor','-d');r'''
 END
     print $gpg_python_code, $e, "'''\n";
+  } elsif ($lang eq 'ruby') {
+    my $gpg_ruby_code = <<'END';
+#!/bin/sh --
+exec ruby -x -- "$0" "$@";exit 1
+#!ruby -w
+f=open(__FILE__);r,w=IO.pipe;q=fork;if q;w.close;STDIN.
+reopen(r);r.close if r.fileno!=0;exec'ruby','-w','-',q.to_s,*ARGV
+end;w<<"[ARGV.delete_at(0).to_i].each{|q|exit(255)if q!=Proc\
+ess.waitpid(q)or$?!=0};";w.flush;ENV['GPG_AGENT_INFO']='';r.
+close;STDIN.reopen(f)if f.fileno!=0;STDOUT.reopen(w)if w.
+fileno!=1;exec'gpg','--armor','-d'
+__END__
+END
+    my $gc = $gpg_ruby_code;
+    $gc =~ s@,'-w',@,@ if not $arg_w;
+    print $gc, $e;
+  } elsif ($lang eq 'perl') {
+    my $gpg_perl_code = <<'END';
+#!/bin/sh --
+exec perl -x -- "$0" "$@";exit 1
+#!perl -w
+my($f,$r,$w);die"error: open self:$!\n"if!open$f,'<',$0;die
+"error: pipe: $!\n"if!pipe$r,$w;my$q=fork;if($q){close($w);if
+(fileno($r)){die"error: reopen stdin: $!\n"if!open STDIN,'<&'
+,fileno($r);close($r)}die"error: exec self: $!\n"if!exec
+'perl','-w','-',$q,@ARGV}die"error: reopen stdout: $1\n"if
+fileno($w)!=1&&!open STDOUT,'>&',fileno($w);print q%BEGIN{m%.
+q%y$q=shift;die"error: waitpid: $!"if $q!=(waitpid($q,0)||0%.
+q%);exit(255)if$?}%;die"error: reopen gpg stdin: $!\n"if
+fileno($f)&&!open STDIN,'<&',fileno($f);$ENV{GPG_AGENT_INFO}=
+'';die"error: exec gpg: $!\n"if!exec'gpg','--armor','-d';
+__END__
+END
+    my $gc = $gpg_perl_code;
+    $gc =~ s@,'-w',@,@ if not $arg_w;
+    print $gc, $e;
   } else {
     die "error: Language not supported in safe mode: $lang\n";
   }
@@ -241,13 +286,6 @@ my $pp2 = prompt_passphrase("Repeat encryption passphrase: ");
 die "error: Passphrases do not match.\n" if $pp ne $pp2;
 my $salt = random(8);  # TODO(pts): Use a better random generator.
 my $key = derive_key($pp, $salt);
-# Add a leading newline as a separator. This screws up line numbering, but
-# we can't add `;' because it's not possible to have a compound statement in
-# the same line. Usually we won't prepend anything, because there is a shebang
-# or a following \n.
-substr($msg, 0, 0) = "\n" if $lang eq 'python' and
-    $msg =~ m/\A(?:\@|(?:from|while|import|with|if|try|class|def|for)\b)/;
-    # $msg !~ m@\A[ \t]*(?:#.*)$@m;
 
 # Overcomes the weaknesses of the non-fully-randomness of initial bytes of RC4.
 # TODO(pts): Would 2 bytes be enough instead of 16?
@@ -331,8 +369,8 @@ q%):sys.exit(255)\ndel a[0]"in{};%;
 END
 my $ruby_pipe_code = << 'END';
  q%[ARGV.delete_%.
-q%at(0).to_i].each{|q|exit(255)if q!=Process.waitpid(q);ARG%.
-q%V.delete_at 0};%;
+q%at(0).to_i].each{|q|exit(255)if q!=Process.waitpid(q)or$?%.
+q%!=0;ARGV.delete_at 0};%;
 END
 my $eval_code = <<'END';
 P="$(P="$P" exec perl -x -- "$0")";test $? = 0||exit 255
