added binary-safe Perl support

diff --git a/encrypt_script b/encrypt_script
--- a/encrypt_script
+++ b/encrypt_script
@@ -7,6 +7,7 @@
 # asks for a passphrase on stderr.
 PERL_BADLANG=x exec perl -x -- "$0" "$@"
 #!perl -w
+# TODO(pts): Fix line numbers because of `perl -x'.
 use integer;
 use strict;
 #** @param $_[0] Binary string.
@@ -93,8 +94,30 @@ my $msg = join('', <STDIN>);
 die "error: NUL not allowed in plaintext\n" if $msg =~ /\0/;
 # TODO(pts): Support bash*, perl*, ruby*, python* etc., also with /usr/bin/env.
 # Don't forget about the `exec <&8 8<&-;' magic added below.
-die "error: Shell script has bad shebang, should be #!/bin/sh\n" if
-    substr($msg, 0, 2) eq '#!' and $msg !~ s@\A#! */bin/sh(?: *--)?\n@@;
+my($type, $perl_w);
+if (substr($msg, 0, 2) eq '#!') {
+  pos($msg) = 0;
+  if ($msg =~ m@^#!(.*perl.*)\n@mg and
+      substr($msg, 0, pos($msg)) =~ y@\n@@ < 16 and
+      (pos($msg) - length($1) == 3 or
+       1)) {  #$msg =~ m@\A#! */bin/(?:ba|da)sh(?: *--)?\n@)) {
+    my $cmd = $1;
+    die if $cmd !~ s@\s*\S+\s*@@;  # Remove the program, keep the argument.
+    $cmd =~ s@\s+\Z(?!\n)@@;
+    $type = 'perl';
+    if ($cmd eq '-w') { $perl_w = ' -w' }
+    elsif ($cmd eq '') { $perl_w = '' }
+    else { die "error: Unsupported Perl shebang flag: $cmd\n" }
+    substr($msg, 0, pos($msg)) = '';  # Remove the shebang line.
+  } elsif ($msg =~ s@\A#! */bin/sh(?: *--)?\n@@) {  # Shell script.
+    $type = 'sh';
+  } else {
+    $msg =~ m@\A(.*)@;
+    die "error: Unrecognized shebang (Perl and shell are allowed): $1\n";
+  }
+} else {
+  $type = 'sh';
+}
 # This acts as a salt and also overcomes the weaknesses of the initial bytes
 # of RC4.
 substr($msg, 0, 0) = random(16);
@@ -123,16 +146,16 @@ print STDERR "info: Wrinting encrypted script to standard output.\n";
 # TODO(pts): Make $0 print the right thing in the shell script. Can it work?
 # TODO(pts): stdin redirection (exec <&8) makes the shell stop reading stdin
 #   in bash 3.2.39.
-print <<'END', $e;
+my $head_code = <<'END';
 #!/bin/sh --
 stty -echo <&2 || exit 124
 echo -n "Enter passphrase for running $0: " >&2
 IFS= read P <&2
 echo >&2; stty echo <&2
 test "$P" || exit 124
-eval "unset P;$(perl -x -- "$0" "$P")"
-#!perl -w
-use integer;use strict;
+END
+my $strict_code="#!perl -w\nuse integer;use strict;\n";
+my $decrypt_code = <<'END';
 sub A($){my$a=1;my$b=0;my$c;for(my$i=0;$i<length$_[0];++$i){my
 $c=vec($_[0],$i,8);$a=($a+$c)%65521;$b=($b+$a)%65521}$b<<16|$a}
 sub D($){my$pp=$_[0];my$key='';my$i=13;while(length$key<1024){
@@ -142,7 +165,7 @@ my$d=unpack('u',join('',<DATA>));
 die"decrypt error: Too short.\n"if!defined($d)||length($d)<24;
 my$a=unpack('N',substr($d,-4));substr($d,-4)='';
 die"decrypt error: Transmission failure.\n"if$a!=A($d);
-{my(@t,@s);my@k=unpack('C*',D($ARGV[0]));my$x=0;my$y=0;
+{my(@t,@s);my@k=unpack('C*',D($ENV{P}));my$x=0;my$y=0;
 for(@t=@s=0..255){$y=($k[$_%@k]+$s[$x=$_]+$y)&255;@s[$x,$y]=
 @s[$y,$x]}for(my$i=0;$i<length$d;++$i){$x++;$y=($s[$x&=255]+
 $y)&255;@s[$x,$y]=@s[$y,$x];vec($d,$i,8)^=$s[($s[$x]+$s[$y])&
@@ -150,3 +173,30 @@ $y)&255;@s[$x,$y]=@s[$y,$x];vec($d,$i,8)^=$s[($s[$x]+$s[$y])&
 die"decrypt error: Bad passphrase.\n"if$a!=A($d);
 substr($d,0,16)='';print$d;__DATA__
 END
+# Don't use eval($d) above, it's not equivalent if the source contains
+# non-printable bytes etc.
+my $perl_pipe_code = <<'END';
+my($r,$w);
+die"error: pipe: $!"if!pipe($r,$w);
+my$q=fork;
+die"error: fork: $!"if!defined$q;
+if ($q) {
+close($w);
+delete $ENV{P};
+if(fileno($r)){
+die"error: redirect stdin: $!\n"if!open STDIN, "<&", fileno($r);
+}
+die"error: exec perl: $!\n"if!exec"perl","-w","-",$q,$0,@ARGV;
+}
+close($r);
+die"error: redirect stdout: $!\n"if!open STDOUT, ">&", fileno($w);
+$|=1;
+print q(BEGIN{my$q=shift;die"error: waitpid: $!"if $q!=(waitpid($q,0)||0);exit(255)if$?;$0=shift});
+END
+if ($type eq 'sh') {
+  print $head_code, 'eval "unset P;$(P="$P" perl -x -- "$0")";exit', "\n",
+        $strict_code, $decrypt_code, $e;
+} elsif ($type eq 'perl') {
+  print $head_code, 'P="$P" exec perl -x "$0" "$@"', "\n",
+        $strict_code, $perl_pipe_code, $decrypt_code, $e;
+}
